baseURL = "https://fervent-blackwell-d718fc.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"

theme = [
  "github.com/zzossig/hugo-theme-zdoc",
  "github.com/zzossig/hugo-theme-zzo"
]

pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsStyle = "monokai"
pygmentsUseClasses = false


[module]

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "archetypes"
  target = "archetypes"

[[module.mounts]]
  source = "data"
  target = "data"



[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true


[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/main"
  weight = 1

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 2