logo = true
logoText = "sigchain capital"
logoType = "short" # long, short
description = "The ZDoc theme for Hugo example site."

themeOptions = ["dark", "light"]

useFaviconGenerator = true # https://www.favicon-generator.org/

enableTocSwitch = true
enableLandingBackground = true
enableSearch = true
enableSearchHighlight = true
enableLangChange = false
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = false

tocLevels = ["h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

#github = "https://github.com/zzossig/hugo-theme-zdoc"

# comment
enableComment = false
disqus_shortname = ""
commento = false


